#pragma once

UENUM(BlueprintType)
enum class EMovingDirection : uint8 {

    EMD_Forward       UMETA(DisplayName = "Forward"),
    EMD_Backward      UMETA(DisplayName = "Backward"),
    EMD_Right         UMETA(DisplayName = "Right"),
    EMD_Left          UMETA(DisplayName = "Left"),
    EMD_ForwardRight  UMETA(DisplayName = "ForwardRight"),
    EMD_ForwardLeft   UMETA(DisplayName = "ForwardLeft"),
    EMD_BackwardRight UMETA(DisplayName = "BackwardRight"),
    EMD_BackwardLeft  UMETA(DisplayName = "BackwardLeft"),

    EMD_Jump               UMETA(DisplayName = "Jump"),
    EMD_Jump_Forward       UMETA(DisplayName = "JumpForward"),
    EMD_Jump_Backward      UMETA(DisplayName = "JumpBackward"),
    EMD_Jump_Right         UMETA(DisplayName = "JumpRight"),
    EMD_Jump_Left          UMETA(DisplayName = "JumpLeft"),
    EMD_Jump_ForwardRight  UMETA(DisplayName = "JumpForwardRight"),
    EMD_Jump_ForwardLeft   UMETA(DisplayName = "JumpForwardLeft"),
    EMD_Jump_BackwardRight UMETA(DisplayName = "JumpBackwardRight"),
    EMD_Jump_BackwardLeft  UMETA(DisplayName = "JumpBackwardLeft"),

    EMD_Jump_Aim               UMETA(DisplayName = "JumpAim"),
    EMD_Jump_Forward_Aim       UMETA(DisplayName = "JumpAimForward"),
    EMD_Jump_Backward_Aim      UMETA(DisplayName = "JumpAimBackward"),
    EMD_Jump_Right_Aim         UMETA(DisplayName = "JumpAimRight"),
    EMD_Jump_Left_Aim          UMETA(DisplayName = "JumpAimLeft"),
    EMD_Jump_ForwardRight_Aim  UMETA(DisplayName = "JumpAimForwardRight"),
    EMD_Jump_ForwardLeft_Aim   UMETA(DisplayName = "JumpAimForwardLeft"),
    EMD_Jump_BackwardRight_Aim UMETA(DisplayName = "JumpAimBackwardRight"),
    EMD_Jump_BackwardLeft_Aim  UMETA(DisplayName = "JumpAimBackwardLeft"),

    EMD_Aim              UMETA(DisplayName = "Aim"),
    EMD_ForwardAim       UMETA(DisplayName = "ForwardAim"),
    EMD_BackwardAim      UMETA(DisplayName = "BackwardAim"),
    EMD_RightAim         UMETA(DisplayName = "RightAim"),
    EMD_LeftAim          UMETA(DisplayName = "LeftAim"),
    EMD_ForwardRightAim  UMETA(DisplayName = "ForwardRightAim"),
    EMD_ForwardLeftAim   UMETA(DisplayName = "ForwardLeftAim"),
    EMD_BackwardRightAim UMETA(DisplayName = "BackwardRightAim"),
    EMD_BackwardLeftAim  UMETA(DisplayName = "BackwardLeftAim"),

    EMD_Crouch              UMETA(DisplayName = "Crouch"),
    EMD_ForwardCrouch       UMETA(DisplayName = "ForwardCrouch"),
    EMD_BackwardCrouch      UMETA(DisplayName = "BackwardCrouch"),
    EMD_RightCrouch         UMETA(DisplayName = "RightCrouch"),
    EMD_LeftCrouch          UMETA(DisplayName = "LeftCrouch"),
    EMD_ForwardRightCrouch  UMETA(DisplayName = "ForwardRightCrouch"),
    EMD_ForwardLeftCrouch   UMETA(DisplayName = "ForwardLeftCrouch"),
    EMD_BackwardRightCrouch UMETA(DisplayName = "BackwardRightCrouch"),
    EMD_BackwardLeftCrouch  UMETA(DisplayName = "BackwardLeftCrouch"),

    EMD_CrouchAim              UMETA(DisplayName = "CrouchAim"),
    EMD_ForwardCrouchAim       UMETA(DisplayName = "ForwardCrouchAim"),
    EMD_BackwardCrouchAim      UMETA(DisplayName = "BackwardCrouchAim"),
    EMD_RightCrouchAim         UMETA(DisplayName = "RightCrouchAim"),
    EMD_LeftCrouchAim          UMETA(DisplayName = "LeftCrouchAim"),
    EMD_ForwardRightCrouchAim  UMETA(DisplayName = "ForwardRightCrouchAim"),
    EMD_ForwardLeftCrouchAim   UMETA(DisplayName = "ForwardLeftCrouchAim"),
    EMD_BackwardRightCrouchAim UMETA(DisplayName = "BackwardRightCrouchAim"),
    EMD_BackwardLeftCrouchAim  UMETA(DisplayName = "BackwardLeftCrouchAim"),

    EMD_Shooting               UMETA(DisplayName = "Shooting"),
    EMD_Forward_Shooting       UMETA(DisplayName = "ForwardShooting"),
    EMD_Backward_Shooting      UMETA(DisplayName = "BackwardShooting"),
    EMD_Right_Shooting         UMETA(DisplayName = "RightShooting"),
    EMD_Left_Shooting          UMETA(DisplayName = "LeftShooting"),
    EMD_ForwardRight_Shooting  UMETA(DisplayName = "ForwardRightShooting"),
    EMD_ForwardLeft_Shooting   UMETA(DisplayName = "ForwardLeftShooting"),
    EMD_BackwardRight_Shooting UMETA(DisplayName = "BackwardRightShooting"),
    EMD_BackwardLeft_Shooting  UMETA(DisplayName = "BackwardLeftShooting"),

    EMD_Jump_Shooting               UMETA(DisplayName = "JumpShooting"),
    EMD_Jump_Forward_Shooting       UMETA(DisplayName = "JumpForwardShooting"),
    EMD_Jump_Backward_Shooting      UMETA(DisplayName = "JumpBackwardShooting"),
    EMD_Jump_Right_Shooting         UMETA(DisplayName = "JumpRightShooting"),
    EMD_Jump_Left_Shooting          UMETA(DisplayName = "JumpLeftShooting"),
    EMD_Jump_ForwardRight_Shooting  UMETA(DisplayName = "JumpForwardRightShooting"),
    EMD_Jump_ForwardLeft_Shooting   UMETA(DisplayName = "JumpForwardLeftShooting"),
    EMD_Jump_BackwardRight_Shooting UMETA(DisplayName = "JumpBackwardRightShooting"),
    EMD_Jump_BackwardLeft_Shooting  UMETA(DisplayName = "JumpBackwardLeftShooting"),

    EMD_Jump_Aim_Shooting               UMETA(DisplayName = "JumpAimShooting"),
    EMD_Jump_Forward_Aim_Shooting       UMETA(DisplayName = "JumpAimForwardShooting"),
    EMD_Jump_Backward_Aim_Shooting      UMETA(DisplayName = "JumpAimBackwardShooting"),
    EMD_Jump_Right_Aim_Shooting         UMETA(DisplayName = "JumpAimRightShooting"),
    EMD_Jump_Left_Aim_Shooting          UMETA(DisplayName = "JumpAimLeftShooting"),
    EMD_Jump_ForwardRight_Aim_Shooting  UMETA(DisplayName = "JumpAimForwardRightShooting"),
    EMD_Jump_ForwardLeft_Aim_Shooting   UMETA(DisplayName = "JumpAimForwardLeftShooting"),
    EMD_Jump_BackwardRight_Aim_Shooting UMETA(DisplayName = "JumpAimBackwardRightShooting"),
    EMD_Jump_BackwardLeft_Aim_Shooting  UMETA(DisplayName = "JumpAimBackwardLeftShooting"),

    EMD_Aim_Shooting              UMETA(DisplayName = "AimShooting"),
    EMD_ForwardAim_Shooting       UMETA(DisplayName = "ForwardAimShooting"),
    EMD_BackwardAim_Shooting      UMETA(DisplayName = "BackwardAimShooting"),
    EMD_RightAim_Shooting         UMETA(DisplayName = "RightAimShooting"),
    EMD_LeftAim_Shooting          UMETA(DisplayName = "LeftAimShooting"),
    EMD_ForwardRightAim_Shooting  UMETA(DisplayName = "ForwardRightAimShooting"),
    EMD_ForwardLeftAim_Shooting   UMETA(DisplayName = "ForwardLeftAimShooting"),
    EMD_BackwardRightAim_Shooting UMETA(DisplayName = "BackwardRightAimShooting"),
    EMD_BackwardLeftAim_Shooting  UMETA(DisplayName = "BackwardLeftAimShooting"),

    EMD_Crouch_Shooting              UMETA(DisplayName = "CrouchShooting"),
    EMD_ForwardCrouch_Shooting       UMETA(DisplayName = "ForwardCrouchShooting"),
    EMD_BackwardCrouch_Shooting      UMETA(DisplayName = "BackwardCrouchShooting"),
    EMD_RightCrouch_Shooting         UMETA(DisplayName = "RightCrouchShooting"),
    EMD_LeftCrouch_Shooting          UMETA(DisplayName = "LeftCrouchShooting"),
    EMD_ForwardRightCrouch_Shooting  UMETA(DisplayName = "ForwardRightCrouchShooting"),
    EMD_ForwardLeftCrouch_Shooting   UMETA(DisplayName = "ForwardLeftCrouchShooting"),
    EMD_BackwardRightCrouch_Shooting UMETA(DisplayName = "BackwardRightCrouchShooting"),
    EMD_BackwardLeftCrouch_Shooting  UMETA(DisplayName = "BackwardLeftCrouchShooting"),

    EMD_CrouchAim_Shooting              UMETA(DisplayName = "CrouchAim"),
    EMD_ForwardCrouchAim_Shooting       UMETA(DisplayName = "ForwardCrouchAim"),
    EMD_BackwardCrouchAim_Shooting      UMETA(DisplayName = "BackwardCrouchAim"),
    EMD_RightCrouchAim_Shooting         UMETA(DisplayName = "RightCrouchAim"),
    EMD_LeftCrouchAim_Shooting          UMETA(DisplayName = "LeftCrouchAim"),
    EMD_ForwardRightCrouchAim_Shooting  UMETA(DisplayName = "ForwardRightCrouchAim"),
    EMD_ForwardLeftCrouchAim_Shooting   UMETA(DisplayName = "ForwardLeftCrouchAim"),
    EMD_BackwardRightCrouchAim_Shooting UMETA(DisplayName = "BackwardRightCrouchAim"),
    EMD_BackwardLeftCrouchAim_Shooting  UMETA(DisplayName = "BackwardLeftCrouchAim"),

    EMD_None UMETA(DisplayName = "None"),

    EMD_MAX UMETA(DisplayName = "Default MAX")

};